### PR TITLE
Addition of save/load and checkboxes

### PR DESCRIPTION
**Pull request by dmolony3**
Hi,

Thanks for developing the MONAIViz extension. While using the extension I made some changes that helped my workflow and I'm interested in sharing them if they can be of benefit to the larger community. There are 2 functionality additions

1. Addition of a checkbox in the first column of the transform table. If the box is checked the transform will run and if not checked it is skipped. This still works with the staged approach but allows someone to run through the entire transform pipeline turning transforms on or off is so desired.
2. Addition of buttons that allow loading and saving transforms as a json file.

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
Can you paste some UI screenshots for these changes..? Will be helpful..

**Comment by dmolony3** [comment]
Here is a screenshot with the addition of load/save transform buttons on the side toolbar. Also, the screenshot shows the resize transform turned off in the table and hence this transform is skipped. Let me know if I can show any more specific images/examples.

image

**Review by SachidanandAlle — APPROVED** [review]

**Comment by wyli** [comment]
Screenshot 2023-08-16 at 12 50 34

I think there's some issue with the loading bundle transforms
Screenshot 2023-08-16 at 12 51 32

could you please help fix this @dmolony3? otherwise I'll try to revert this PR commit...

**Comment by dmolony3** [comment]
Hi @wyli. I had not tried the bundle transforms. I'll take a look at it this morning.

**Comment by wyli** [comment]
many thanks! (to replicate the issue, start the MONAIViz module using the latest codebase, then click the blue downloading icon next to "spleen_ct-segmentation pre")

**Comment by dmolony3** [comment]
Everything should be ok now. I confirmed that the spleen segmentation transforms worked ok. Should I create a new pull request for these changes?

**Pull request merged**
